### PR TITLE
PhpStorm code inspection cleanups

### PR DESCRIPTION
**Pull request by Jalle19**
This fixes most issues, there are a few left, practically all stemming from the slightly sloppy usage of traits for fields and types. I figured it's not worth trying to work around those with phpdoc annotations, instead they should ideally be refactored somewhat.

The most notable changes are:

* https://github.com/digiaonline/GraphQL/commit/248f0ae44e6b2783d64ffe56933acec1c1249397 removes a `new ResolveInfo` call, may speed things up a tiny bit
* https://github.com/digiaonline/GraphQL/commit/c422fc044408259ad512f579d9f4bc94f17df254 removes two unused traits. They have been marked as deprecated and the TODO says they should be removed in the next release, so I figured why not.

### CODE REVIEW

**Comment by Jalle19** [comment]
Scrutinizer seems to be happy at least:

> Good job, 12 issues were fixed.

> Test Coverage has increased to 91% (+2%)

**Comment by viniychuk** [comment]
Everything looks fine except the removal of the DirectiveTrait. It was WIP that got merged into the branch, but it will be used in the future release. Can you revert that one?

**Comment by Jalle19** [comment]
Sure, I'll drop that commit

**Comment by Jalle19** [comment]
@viniychuk done

**Comment by viniychuk** [comment]
@Jalle19 sorry, if you could fix the conflicts — I'll merge it again and publish today

**Comment by Jalle19** [comment]
@viniychuk I'm at a hotel with restricted Internet but I'll rebase next weekend or when I find a better connection.

**Comment by Jalle19** [comment]
@viniychuk rebased

**Comment by Jalle19** [comment]
@viniychuk are the tests supposed to pass?

**Comment by Jalle19** [comment]
https://travis-ci.org/Youshido/GraphQL/jobs/259325602 apparently not

**Comment by viniychuk** [comment]
The master branch is fixed. I was looking through the changes and have noticed this: http://take.ms/G4q4L — got it restored.

**Comment by Jalle19** [comment]
Not really sure what you mean, but thanks for merging.

**Pull request merged**
