### PR TITLE
Merged deferred resolvers.

### PR DESCRIPTION
**Pull request by fubhy**

### CODE REVIEW

**Comment by viniychuk** [comment]
@fubhy @pmelab there're tests failing after merge... could someone check on your side? :)

**Comment by pmelab** [comment]
@viniychuk Is it not possible any more to have 2 top level fields in the same query?

This ...

```
query {
  a:users(ids: ["a"]) {
     name
  }
  b:users(ids: ["b"]) {
    name
  }
}
```

.. breaks with `Unexpected token "IDENTIFIER"` at `b:users` (or more specific the "b" token). And we didn't touch the parser.

**Comment by fritz-gerneth** [comment]
@pmelab I reported this as a failing test over here already: https://github.com/Youshido/GraphQL/pull/160

**Comment by viniychuk** [comment]
@pmelab sorry this is our bad, will try to fix it tonight

**Comment by fubhy** [comment]
Any news on this?

**Comment by viniychuk** [comment]
@fubhy the problem only occurred when you say "query" at the beginning... fixing it

**Comment by viniychuk** [comment]
@fubhy , @pmelab fixed.

**Pull request merged**
