### PR TITLE
Fix code that would run into arbitrary date comparison failures, partly caused by backwards-incompatible changes in PHP 7.1.

### PR DESCRIPTION
**Pull request by bartfeenstra**
One of the test fixtures was a little unstable already, because it would compare individually instantiated times and assume they'd be identical (which would fail if the test was run exactly when the clock changed). PHP 7.1 also introduced a [backwards-incompatible change](http://php.net/manual/en/migration71.incompatible.php#migration71.incompatible.datetime-microseconds) to `\DateTime('now')`, which these same fixtures uses, exacerbating the problem. This PR fixes both issues.

### CODE REVIEW

**Comment by viniychuk** [comment]
Thanks for the update, I'll check with the team and merge it if we don't have it yet in 2.0 that is in development right now.

**Comment by bartfeenstra** [comment]
@viniychuk Thanks for the response! Even if this is in 2.0 already, we won't be switching major versions anytime soon. Would this be eligible for inclusion in 1.x?

**Comment by viniychuk** [comment]
@bartfeenstra this one is already implemented on our side and merged in current master, will be release in 1.5 this week together with your other PR.

**Comment by bartfeenstra** [comment]
@viniychuk Thanks for your response, but it's a bit confusing, because, these changes [do not exist in master](https://github.com/Youshido/GraphQL/blob/master/Tests/DataProvider/TestScalarDataProvider.php) yet.

**Comment by viniychuk** [comment]
@bartfeenstra it's weird. Let me check and make sure they are :)

**Comment by bartfeenstra** [comment]
Thanks!

**Pull request merged**
