### PR TITLE
Replace closures in introspection to enable serialization.

### PR DESCRIPTION
**Pull request by fubhy**

### CODE REVIEW

**Comment by dawehner** [comment]
Can we have some test coverage which has serialization to ensure this actually could work?

**Comment by fubhy** [comment]
That's already part of the PR. I added a small test case that serializes and unserializes and checks the integrity of the schema afterwards.

**Comment by fubhy** [comment]
@viniychuk anything missing here? :)

**Comment by viniychuk** [comment]
It's all good, thanks @fubhy

**Pull request merged**
