### PR TITLE
Merged deferred branch again with error handling.

### PR DESCRIPTION
**Pull request by fubhy**

### CODE REVIEW

**Comment by fubhy** [comment]
Sorry, Philipp did another PR on the deferred branch which was not included last time :)

**Comment by viniychuk** [comment]
Merging, will write a short description and publish now

**Comment by fubhy** [comment]
Thanks!

**Comment by fubhy** [comment]
I just noticed that the master branch is now failing: https://travis-ci.org/Youshido/GraphQL/jobs/259325601

**Comment by fritz-gerneth** [comment]
You have added some tests for querying multiple root fields which I reported here https://github.com/Youshido/GraphQL/pull/160 with a few additional tests

**Pull request merged**
