### PR TITLE
Recursive deferred resolvers.

### PR DESCRIPTION
**Pull request by pmelab**
Added test cases for deferred resolving and adapted the processor to properly evaluate nested resolvers level by level.

### CODE REVIEW

**Comment by fubhy** [comment]
Lovely. There are, however, a few unrelated indentation changes. Makes it a bit harder to review (the second half of the PR can be skipped). Mind reverting those?

**Comment by fubhy** [comment]
Oh sorry, I didn't see the closure opening.

**Comment by pmelab** [comment]
@portey thanks for the review! I used it for good, and the implementation is more elegant now. There a no more "scan" steps. Instead the processor adds deferred resolvers to the queue whenever it stumbles upon them.

I also added a streamlined `DeferredResolverInterface` (and `DeferredResult` has been  re-purposed in the process).

**Comment by viniychuk** [comment]
@pmelab @portey Well done guys!

**Comment by fubhy** [comment]
Are you going to merge and publish the contents of the "deferred" branch any time soon?

**Comment by armetiz** [comment]
Good job guys!
You just need to add some documentation ;p

**Comment by dilab** [comment]
Is DeferredResolver some kind of cache resolver? Not the _defer_ feature of GraphQL mentioned in this post https://dev-blog.apollodata.com/new-features-in-graphql-batch-defer-stream-live-and-subscribe-7585d0c28b07.

Am I right?

**Comment by pmelab** [comment]
Deferred resolvers are collected in the result tree to be evaluated at once (if the query requests different 5 database objects, they can be loaded with a single query). So they don't directly relate to the deferred feature.

But they are similar and I wonder if deferred resolvers are already a suitable backend solution for a `@defer` directive.

**Comment by dilab** [comment]
@pmelab thanks for the clarification. I can see how **DeferredResover**  can improve the performance. 
Any plan to release a simple documentation on how to use it properly?

**Comment by viniychuk** [comment]
@dilab yep... hopefuly on the weekend

**Comment by dilab** [comment]
@viniychuk awesome! cant wait

**Comment by dilab** [comment]
@viniychuk understood you are super busy. If you could provide me some simple samples, i will be happy to write tutorials for this section.

**Comment by armetiz** [comment]
any news ?

**Comment by dilab** [comment]
@pmelab will you add some documentation on how to use your PR?

**Comment by fritz-gerneth** [comment]
You can always have a look at the tests included. Besides testing they are some kind of documentation as well, right? :) 
Relevant files are [DeferredTest](https://github.com/Youshido/GraphQL/blob/master/Tests/Schema/DeferredTest.php) and [DeferredResolver](https://github.com/Youshido/GraphQL/blob/master/src/Execution/DeferredResolver.php).

The implementation is rather simple. In your resolve function, instead of returning the value right away, return a new instance of `DeferredResolver`. The only argument for the `DeferredResolver` is the callable you want to be called later on. 

The test file above actually exactly shows a demo on how to defer ([call](https://github.com/Youshido/GraphQL/blob/master/Tests/Schema/DeferredTest.php#L61)) & [bulk query](https://github.com/Youshido/GraphQL/blob/master/Tests/Schema/DeferredTest.php#L73) the database.

**Pull request merged**
