### PR TITLE
Do not validate schema in processor

### PR DESCRIPTION
**Pull request by fubhy**
Validating the schema in the processor means that, even when the schema is cached, you have to re-validate it although you can guarantee that it is the same as last time you can validation. This should be an implementation detail and part of the application code that integrates with this library.

### CODE REVIEW

**Comment by fubhy** [comment]
We should consider updating the README accordingly.

**Comment by fubhy** [comment]
Merging this with https://github.com/Youshido/GraphQL/pull/36

**Comment by portey** [comment]
Hi, @fubhy 

perhaps it's better to add a new parameter to the constructor of Proccessor, witch be control use validation or not. As you say?

**Comment by fubhy** [comment]
I understand that you want to keep the integration code as small as possible. I think an extra argument is not the right approach however. Let's add an additional class "Executor" like on the JS implementation that comes with this as default and initializes the processor, validates the schema and runs the query

**Pull request closed without merging**
