### PR TITLE
Fixing possibleTypes field in introspection.

### PR DESCRIPTION
**Pull request by fubhy**

### CODE REVIEW

**Comment by fubhy** [comment]
@viniychuk Hi! This PR fixes the possibleTypes field response when the possible types are not directly part of the schema at any place as a concrete type but only through a reference in union/interface. When calling possibleTypes on the interface in this case you currently do not get these types in the response. This PR fixes that.

**Comment by fritz-gerneth** [comment]
I assume this would also fix #122 ? :)

**Comment by fubhy** [comment]
Yes. I think so. @viniychuk any plans on merging this? :)

**Comment by viniychuk** [comment]
@fubhy wanted to do something different here but as you can tell – haven't got a chance :) 
Merged

**Pull request merged**
